"""Construction de theme.txt via templates.

Single responsibility: produire le texte final à partir d'une config.
"""

from __future__ import annotations

import logging
from typing import Any

from .core_theme_generator_models import ResolutionConfig

logger = logging.getLogger(__name__)


class ThemeTemplateBuilder:
    """Construit des fichiers de thème GRUB à partir de templates."""

    THEME_HEADER = """\
# GRUB2 gfxmenu Linux theme
# {title}
# Elements: {elements_list}
# Generated by 05_xxx
"""

    GLOBAL_PROPS = """
# Global Properties
title-text: ""
desktop-image: "{desktop_image}"
desktop-image-scale-method: "{scale_method}"
desktop-image-h-align: "{h_align}"
desktop-image-v-align: "{v_align}"
desktop-color: "{background_color}"
terminal-font: "{terminal_font}"
terminal-box: "terminal_box_*.png"
terminal-width: "100%"
terminal-height: "100%"
terminal-border: "0"
"""

    BOOT_MENU_TEMPLATE = """
# Boot Menu Component
+ boot_menu {{
  left = {left}%
  top = {top}%
  width = {width}%
  height = {height}%
  item_font = "{item_font}"
  item_color = "{item_color}"
  selected_item_color = "{selected_item_color}"
  icon_width = {icon_size}
  icon_height = {icon_size}
  item_icon_space = 20
  item_height = {item_height}
  item_padding = 5
  item_spacing = {item_spacing}
  selected_item_pixmap_style = "{selection_style}"
}}
"""

    PROGRESS_BAR_TEMPLATE = """
# Progress Bar Component
+ progress_bar {{
  id = "__timeout__"
  left = 50%-{width_half}%
  top = {top}%
  width = {width}%
  height = {height}
  text_color = "{fg_color}"
  bg_color = "{bg_color}"
  fg_color = "{fg_color}"
  bar_style = "progress_bar_*.png"
}}
"""

    TIMEOUT_LABEL_TEMPLATE = """
# Timeout Label
+ label {{
  top = {top}%
  left = 32%
  width = 36%
  align = "center"
  id = "__timeout__"
  text = "{text}"
  color = "{color}"
  font = "{font}"
}}
"""

    IMAGE_TEMPLATE = """
# Info/Footer Image
+ image {{
  top = 100%-{height}
  left = 50%-{width_half}
  width = {width}
  height = {height}
  file = "{file}"
}}
"""

    LOGO_TEMPLATE = """
# Logo Image
+ image {{
  top = {top}%
  left = 50%-{width_half}
  width = {width}
  height = {height}
  file = "{file}"
}}
"""

    LABEL_TEMPLATE = """
# Generic Label
+ label {{
  top = {top}%
  left = {left}%
  width = {width}%
  align = "{align}"
  text = "{text}"
  color = "{color}"
  font = "{font}"
}}
"""

    @staticmethod
    def generate_theme_file(title: str, config: dict[str, Any], resolution_config: ResolutionConfig) -> str:
        """Génère le contenu de theme.txt."""
        elements_config: dict[str, Any] = config.get("elements", {})
        properties: dict[str, Any] = config.get("properties", {})

        parts: list[str] = [
            ThemeTemplateBuilder._build_header(title, elements_config),
            ThemeTemplateBuilder._build_global_props(properties, resolution_config),
            ThemeTemplateBuilder._build_boot_menu(elements_config, properties, resolution_config),
            ThemeTemplateBuilder._build_progress_bar(elements_config, properties),
            ThemeTemplateBuilder._build_timeout_label(elements_config, properties, resolution_config),
            ThemeTemplateBuilder._build_footer_image(elements_config, properties, resolution_config),
            ThemeTemplateBuilder._build_logo_image(elements_config, properties),
            ThemeTemplateBuilder._build_instruction_label(elements_config, properties, resolution_config),
        ]

        content = "".join(p for p in parts if p)
        logger.info("Generated dynamic theme file for %s", title)
        return content

    @staticmethod
    def build_theme_file(title: str, config: dict[str, Any], resolution_config: ResolutionConfig) -> str:
        """Alias public pour générer un theme.txt."""
        return ThemeTemplateBuilder.generate_theme_file(title=title, config=config, resolution_config=resolution_config)

    @staticmethod
    def _build_header(title: str, elements_config: dict[str, Any]) -> str:
        enabled_elements = [name for name, e in elements_config.items() if e.get("enabled")]
        return ThemeTemplateBuilder.THEME_HEADER.format(
            title=title,
            elements_list=", ".join(enabled_elements),
        )

    @staticmethod
    def _build_global_props(properties: dict[str, Any], resolution_config: ResolutionConfig) -> str:
        colors = properties.get("colors", {})
        fonts = properties.get("fonts", {})
        desktop_image_props = properties.get("desktop_image", {})
        return ThemeTemplateBuilder.GLOBAL_PROPS.format(
            background_color=desktop_image_props.get("background_color", colors.get("background", "#000000")),
            terminal_font=fonts.get("terminal_font", f"Terminus Regular {resolution_config.terminal_font_size}"),
            desktop_image=desktop_image_props.get("file", "background.jpg").split("/")[-1],
            scale_method=desktop_image_props.get("scale_method", "stretch"),
            h_align=desktop_image_props.get("h_align", "center"),
            v_align=desktop_image_props.get("v_align", "center"),
        )

    @staticmethod
    def _build_boot_menu(
        elements_config: dict[str, Any],
        properties: dict[str, Any],
        resolution_config: ResolutionConfig,
    ) -> str:
        if not elements_config.get("boot_menu", {}).get("enabled"):
            return ""

        boot_menu_props = properties.get("boot_menu", {})
        icons_props = properties.get("icons", {})
        colors = properties.get("colors", {})
        fonts = properties.get("fonts", {})

        icon_size = icons_props.get("icon_size", boot_menu_props.get("icon_size", 32))
        selection_style = "select_*.png"
        _ = elements_config.get("selection", {}).get("enabled")

        return ThemeTemplateBuilder.BOOT_MENU_TEMPLATE.format(
            left=boot_menu_props.get("left", 30),
            top=boot_menu_props.get("top", 30),
            width=boot_menu_props.get("width", 40),
            height=boot_menu_props.get("height", 40),
            item_font=fonts.get("item_font", f"Unifont Regular {resolution_config.item_font_size}"),
            item_color=colors.get("text", "#cccccc"),
            selected_item_color=colors.get("selected", "#ffffff"),
            icon_size=icon_size,
            item_height=boot_menu_props.get("item_height", 36),
            item_spacing=boot_menu_props.get("item_spacing", 10),
            selection_style=selection_style,
        )

    @staticmethod
    def _build_progress_bar(elements_config: dict[str, Any], properties: dict[str, Any]) -> str:
        if not elements_config.get("progress_bar", {}).get("enabled"):
            return ""

        pb_props = properties.get("progress_bar", {})
        colors = properties.get("colors", {})
        width = pb_props.get("width", 60)
        return ThemeTemplateBuilder.PROGRESS_BAR_TEMPLATE.format(
            top=pb_props.get("top", 80),
            width=width,
            width_half=width // 2,
            height=pb_props.get("height", 24),
            fg_color=pb_props.get("fg_color", colors.get("selected_bg", "#cccccc")),
            bg_color=pb_props.get("bg_color", "#333333"),
        )

    @staticmethod
    def _build_timeout_label(
        elements_config: dict[str, Any],
        properties: dict[str, Any],
        resolution_config: ResolutionConfig,
    ) -> str:
        if not elements_config.get("timeout_label", {}).get("enabled"):
            return ""

        timeout_props = properties.get("timeout_label", {})
        colors = properties.get("colors", {})
        fonts = properties.get("fonts", {})
        return ThemeTemplateBuilder.TIMEOUT_LABEL_TEMPLATE.format(
            top=timeout_props.get("top", 82),
            text=timeout_props.get("text", "Booting in %d seconds"),
            color=colors.get("label", colors.get("text", "#cccccc")),
            font=fonts.get("item_font", f"Unifont Regular {resolution_config.item_font_size}"),
        )

    @staticmethod
    def _build_footer_image(
        elements_config: dict[str, Any],
        properties: dict[str, Any],
        resolution_config: ResolutionConfig,
    ) -> str:
        if not elements_config.get("footer_image", {}).get("enabled"):
            return ""

        footer_props = properties.get("footer_image", {})
        height = footer_props.get("height", 42)
        width = resolution_config.width // 3
        return ThemeTemplateBuilder.IMAGE_TEMPLATE.format(
            height=height,
            width=width,
            width_half=width // 2,
            file=footer_props.get("file", "info.png").split("/")[-1],
        )

    @staticmethod
    def _build_logo_image(elements_config: dict[str, Any], properties: dict[str, Any]) -> str:
        if not elements_config.get("logo_image", {}).get("enabled"):
            return ""

        logo_props = properties.get("logo_image", {})
        width = logo_props.get("width", 256)
        return ThemeTemplateBuilder.LOGO_TEMPLATE.format(
            top=logo_props.get("top", 10),
            width=width,
            width_half=width // 2,
            height=logo_props.get("height", 128),
            file=logo_props.get("file", "logo.png").split("/")[-1],
        )

    @staticmethod
    def _build_instruction_label(
        elements_config: dict[str, Any],
        properties: dict[str, Any],
        resolution_config: ResolutionConfig,
    ) -> str:
        if not elements_config.get("instruction_label", {}).get("enabled"):
            return ""

        label_props = properties.get("instruction_label", {})
        colors = properties.get("colors", {})
        fonts = properties.get("fonts", {})
        return ThemeTemplateBuilder.LABEL_TEMPLATE.format(
            top=label_props.get("top", 85),
            left=label_props.get("left", 0),
            width=label_props.get("width", 100),
            align=label_props.get("align", "center"),
            text=label_props.get(
                "text",
                "Appuyez sur 'e' pour éditer, 'c' pour la ligne de commande",
            ),
            color=label_props.get(
                "color",
                colors.get("label", colors.get("text", "#aaaaaa")),
            ),
            font=fonts.get("item_font", f"Unifont Regular {resolution_config.item_font_size}"),
        )
